package Mod;
import Mod.EquationMeth;
import Mod.problemSelect;

import javax.swing.*;
import java.awt.*;
import java.util.Objects;


/*
* Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
* Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
*/

/**
*
* @author david
*/
//allows use to choose grade level for problems
public class GradeChooser extends javax.swing.JFrame {

	Image img = new ImageIcon(Objects.requireNonNull(this.getClass().getResource("/images/math.png"))).getImage();
    boolean loop = true;
   /**
    * Creates new form GradeChooser
    */
    
   //creates the screen and buttons to use
   public GradeChooser() {
	   
       initComponents();
       jButton1.setBackground(Color.RED);
       jButton2.setBackground(Color.GREEN);
       jButton3.setBackground(Color.BLUE);
       jButton4.setBackground(Color.YELLOW);
       jLabel1.setText("");
       Dimension size = Toolkit. getDefaultToolkit(). getScreenSize();
       int scrnH = size.height;
       int scrnW = size.width;
       Dimension o =getSize();
       int Hdia = o.height/2;
       int Wdia = o.width/2;

       setLocation(scrnW/2-Wdia,scrnH/2-Hdia);
	   
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">
   //starts up screen and buttons and make sure they notice when used.
   private void initComponents() {

	   jLabel1 = new javax.swing.JLabel();
       jTextField1 = new javax.swing.JTextField();
       jButton1 = new javax.swing.JButton();
       jButton2 = new javax.swing.JButton();
       jButton3 = new javax.swing.JButton();
       jButton4 = new javax.swing.JButton();
       jLabel2 = new javax.swing.JLabel();

       setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

       jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doing matj.png"))); // NOI18N
       jLabel1.setText("jLabel1");

       jTextField1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
       jTextField1.setText("SELECT A GRADE LEVEL");

       jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
       jButton1.setText("1st Grade");
       jButton1.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton1ActionPerformed(evt);
           }
       });

       jButton2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
       jButton2.setText("2nd Grade");
       jButton2.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton2ActionPerformed(evt);
           }
       });

       jButton3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
       jButton3.setText("3rd Grade");
       jButton3.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton3ActionPerformed(evt);
           }
       });

       jButton4.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
       jButton4.setText("4th Grade");
       jButton4.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton4ActionPerformed(evt);
           }
       });

       jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
       jLabel2.setText("CLICK THE X AT THE TOP TO EXIT");
       jLabel2.setToolTipText("");

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(18, 18, 18)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jTextField1)
                   .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addGroup(layout.createSequentialGroup()
                       .addComponent(jLabel2)
                       .addGap(0, 0, Short.MAX_VALUE)))
               .addContainerGap())
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(layout.createSequentialGroup()
                       .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                   .addGroup(layout.createSequentialGroup()
                       .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addGap(18, 18, 18)
                       .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addGap(18, 18, 18)
                       .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                       .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                       .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                       .addComponent(jLabel2)
                       .addGap(72, 72, 72))))
       );

       pack();
   }// </editor-fold>                        
// </editor-fold>                        
   // if button 1 is selected the grade level will be 1 and difficulty for the problems will be set to 5.
   //will also move onto next type of problem selection screen
   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
	   
       problemSelect o = new problemSelect(5);
       setVisible(false); //you can't see me!
//Destroy the JFrame object
       o.setVisible(true);
       o.isVisible();
	   
   }
   // if button 2 is selected the grade level will be 2 and difficulty for the problems will be set to 8.
   //will also move onto next type of problem selection screen
   private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
	  
       problemSelect o = new problemSelect(8);
       setVisible(false); //you can't see me!
 //Destroy the JFrame object
       o.setVisible(true);
       o.isVisible();
	   
   }
   // if button 3 is selected the grade level will be 3 and difficulty for the problems will be set to 10.
   //will also move onto next type of problem selection screen
   private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
	   
       problemSelect o = new problemSelect(10);
       setVisible(false); //you can't see me!
 //Destroy the JFrame object
       o.setVisible(true);
       o.isVisible();
	   
   }
   // if button 4 is selected the grade level will be 4 and difficulty for the problems will be set to 25.
   //will also move onto next type of problem selection screen
   private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
	   
       problemSelect o = new problemSelect(25);
       setVisible(false); //you can't see me!
//Destroy the JFrame object
       o.setVisible(true);
       o.isVisible();
	   
   }
   


   /**
    * @param args the command line arguments
    */
   //creates buttons and screen to be used and runs them.
   public static void main(String args[]) {
       /* Set the Nimbus look and feel */
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
       /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
       try {
           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               if ("Nimbus".equals(info.getName())) {
                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   break;
               }
           }
       } catch (ClassNotFoundException ex) {
           java.util.logging.Logger.getLogger(GradeChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (InstantiationException ex) {
           java.util.logging.Logger.getLogger(GradeChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (IllegalAccessException ex) {
           java.util.logging.Logger.getLogger(GradeChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (javax.swing.UnsupportedLookAndFeelException ex) {
           java.util.logging.Logger.getLogger(GradeChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       }
       //</editor-fold>

       /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
               new GradeChooser().setVisible(true);
           }
       });
   }

   // Variables declaration - do not modify                     
   // Variables declaration - do not modify                     
   private javax.swing.JButton jButton1;
   private javax.swing.JButton jButton2;
   private javax.swing.JButton jButton3;
   private javax.swing.JButton jButton4;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JTextField jTextField1;
   // End of variables declaration                         
}
