package Mod;
import Mod.questions;

import java.awt.*;

/*
* Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
* Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
*/

/**
*
* @author 
*/

//allows user to set types of problems to take and the ammount of problems
public class problemSelect extends javax.swing.JFrame {

   /**
    * Creates new form problemSelect
    */

   int gradeLevel;
   private boolean sub = false;
   private boolean add = false;
   private boolean mult = false;
   private boolean div = false;

   private int clickCounter = 0;
   private int clickCounter2 = 0;
   private int clickCounter3 = 0;
   private int clickCounter4 = 0;

   //creates a new screen for selecting the problem types and how many problems and makes the buttons
   public problemSelect(int num) {
       gradeLevel = num;
       System.out.print(gradeLevel);
       initComponents();
       Dimension size = Toolkit. getDefaultToolkit(). getScreenSize();
       int scrnH = size.height;
       int scrnW = size.width;
       Dimension o =getSize();
       int Hdia = o.height/2;
       int Wdia = o.width/2;
       setLocation(scrnW/2-Wdia,scrnH/2-Hdia);
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">

  
   //creates the Jframe and buttons to use as well as text bar to type number of questions
   private void initComponents() {

	   jToggleButton1 = new javax.swing.JToggleButton();
       jToggleButton2 = new javax.swing.JToggleButton();
       jToggleButton3 = new javax.swing.JToggleButton();
       jToggleButton4 = new javax.swing.JToggleButton();
       jLabel1 = new javax.swing.JLabel();
       jButton1 = new javax.swing.JButton();
       jLabel2 = new javax.swing.JLabel();
       jTextField1 = new javax.swing.JTextField();

       setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
       setBackground(new java.awt.Color(150, 150, 10));

       jToggleButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
       jToggleButton1.setText("Subtraction");
       jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jToggleButton1ActionPerformed(evt);
           }
       });

       jToggleButton2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
       jToggleButton2.setText("Addition");
       jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jToggleButton2ActionPerformed(evt);
           }
       });

       jToggleButton3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
       jToggleButton3.setText("Multiplication");
       jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jToggleButton3ActionPerformed(evt);
           }
       });

       jToggleButton4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
       jToggleButton4.setText("Divison");
       jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jToggleButton4ActionPerformed(evt);
           }
       });

       jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
       jLabel1.setText("TOOGLE WHICH SUBJECTS YOU WOULD LIKE TO WORK ON");

       jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
       jButton1.setText("Click Me to enter selected");
       jButton1.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton1ActionPerformed(evt);
           }
       });

       jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
       jLabel2.setText("Number of Questions");

       jTextField1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                   .addGroup(layout.createSequentialGroup()
                       .addGap(38, 38, 38)
                       .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                   .addGroup(layout.createSequentialGroup()
                       .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                       .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                       .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addGap(10, 10, 10)
                       .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
               .addContainerGap())
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(33, 33, 33)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addGap(46, 46, 46)
               .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(18, 18, 18)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                       .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                   .addComponent(jToggleButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGap(37, 37, 37)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addGroup(layout.createSequentialGroup()
                       .addComponent(jLabel2)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                       .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
               .addContainerGap(38, Short.MAX_VALUE))
       );

       pack();
   }// </editor-fold>

   //makes it so that if the subtraction button is selected/unselected, the question will reflect this
   //when selection is completed
   private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {
       if(clickCounter%2==0) {
           sub = true;
           clickCounter++;
       }
       else if(clickCounter%2!=0){
           sub = false;
           clickCounter++;
       }
   }
   //makes it so that if the addition button is selected/unselected, the question will reflect this
   //when selection is completed
   private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {
       if(clickCounter2%2==0) {
           add = true;
           clickCounter2++;
       }
       else if(clickCounter2%2!=0){
           add = false;
           clickCounter2++;
       }
   }
   //makes it so that if the multiplication button is selected/unselected, the question will reflect this
   //when selection is completed
   private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {
       if(clickCounter3%2==0) {
           mult = true;
           clickCounter3++;
       }
       else if(clickCounter3%2!=0){
           mult = false;
           clickCounter3++;
       }
   }
   //makes it so that if the division button is selected/unselected, the question will reflect this
   //when selection is completed
   private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {
       if(clickCounter4%2==0) {
           div = true;
           clickCounter4++;
       }
       else if(clickCounter4%2!=0){
           div = false;
           clickCounter4++;
       }
   }

   //finalizes selection for type of question and number and moves onto problem screen.
   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
       questions o = new questions(add,sub,mult,div,Integer.parseInt(jTextField1.getText()),gradeLevel);
       setVisible(false); //you can't see me!
       dispose(); //Destroy the JFrame object
       o.setVisible(true);
       o.isVisible();
   }

   /**
    * @param args the command line arguments
    */
   //runs class and methods
   public static void main(String args[]) {
       /* Set the Nimbus look and feel */
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
       /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
       try {
           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               if ("Nimbus".equals(info.getName())) {
                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   break;
               }
           }
       } catch (ClassNotFoundException ex) {
           java.util.logging.Logger.getLogger(problemSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (InstantiationException ex) {
           java.util.logging.Logger.getLogger(problemSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (IllegalAccessException ex) {
           java.util.logging.Logger.getLogger(problemSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (javax.swing.UnsupportedLookAndFeelException ex) {
           java.util.logging.Logger.getLogger(problemSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       }
       //</editor-fold>

       /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
               new problemSelect(1).setVisible(true);
           }
       });
   }

   private javax.swing.JButton jButton1;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JTextField jTextField1;
   private javax.swing.JToggleButton jToggleButton1;
   private javax.swing.JToggleButton jToggleButton2;
   private javax.swing.JToggleButton jToggleButton3;
   private javax.swing.JToggleButton jToggleButton4;
   // End of variables declaration                   
}