       package Mod;
       import javax.swing.JOptionPane;
       import Mod.GradeChooser;
       import Mod.questionsAnswered;
       import Viewcon.Controller;

       import Mod.EquationMeth;

       import java.awt.*;
       import java.util.ArrayList;

       /*
* Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
* Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
*/

/**
*
* @author david
*/
//provides a screen to show users the questions and a space to answer and a button to enter answer.
public class questions extends javax.swing.JFrame {

   private boolean sub;
   private Controller cnt = new Controller();
   private boolean add;
   private boolean mult;
   private boolean div;
   private int numProblems;
   private int problemsDone = 0;
   private int gradeLVL;
   private int numCorrect = 0;
   private ArrayList<questionsAnswered> PP = new ArrayList<>();
   EquationMeth o;

   /**
    * Creates new form questions
    */
   //creates parts of the screen, the button, and the typing area
   public questions(boolean a, boolean s, boolean m, boolean d,int num, int grd) {
       add = a;
       sub = s;
       mult = m;
       div = d;
       numProblems = num;
       gradeLVL = grd;
       o= new EquationMeth(add,sub,mult,div,numProblems,grd);

       System.out.print("" +add+sub+mult+div+numProblems+gradeLVL);
       initComponents();
       Dimension size = Toolkit. getDefaultToolkit(). getScreenSize();
       int scrnH = size.height;
       int scrnW = size.width;
       Dimension ok =getSize();
       int Hdia = ok.height/2;
       int Wdia = ok.width/2;
       setLocation(scrnW/2-Wdia,scrnH/2-Hdia);
       jTextField1.setText("enter answer");
       jTextField1.select(0, jTextField1.getText().length());
       jProgressBar1.setMaximum(numProblems);
       jProgressBar1.setBackground(Color.WHITE);
       jProgressBar1.setForeground(Color.blue);
       jLabel1.setText(o.chooseEquation());

   }


   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">
   //starts up the screen and makes it so the typing are and buttons work
   private void initComponents() {

       jColorChooser1 = new javax.swing.JColorChooser();
       jLabel1 = new javax.swing.JLabel();
       jProgressBar1 = new javax.swing.JProgressBar();
       jTextField1 = new javax.swing.JTextField();
       jButton1 = new javax.swing.JButton();

       setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

       jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
       jLabel1.setText("jLabel1");

       jTextField1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
       jTextField1.setText("jTextField1");

       jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
       jButton1.setText("Submit");
       jButton1.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton1ActionPerformed(evt);
           }
       });

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                       .addGroup(layout.createSequentialGroup()
                               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addGroup(layout.createSequentialGroup()
                                               .addGap(39, 39, 39)
                                               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                       .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                       .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                                                       .addComponent(jTextField1)))
                                       .addGroup(layout.createSequentialGroup()
                                               .addGap(150, 150, 150)
                                               .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                               .addContainerGap(61, Short.MAX_VALUE))
       );
       layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                       .addGroup(layout.createSequentialGroup()
                               .addContainerGap()
                               .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                               .addGap(18, 18, 18)
                               .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                               .addGap(28, 28, 28)
                               .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                               .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                               .addContainerGap())
       );

       pack();
   }// </editor-fold>
   //takes given answer to problem in the typing area, checks if the answer is correct and keeps this information
   //and moves on to the next question. If done with all the questions displays score and questions wrong
   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
       boolean answ = o.checkAnswer(Integer.parseInt(jTextField1.getText()),o.getAnswer());
       PP.add(new questionsAnswered(jLabel1.getText(), o.getAnswer(), answ, Integer.parseInt(jTextField1.getText())));
       problemsDone++;
       jProgressBar1.setValue(jProgressBar1.getValue()+1);
       jProgressBar1.update(jProgressBar1.getGraphics());
       
       if(answ) {
           JOptionPane.showMessageDialog(jButton1, "Correct");
           numCorrect++;
       }
       else {
           JOptionPane.showMessageDialog(jButton1, "Incorrect");
       }
       
       if(problemsDone<numProblems) {
           jLabel1.setText(o.chooseEquation());

       }
       else{
           setVisible(false);
           int percent  = (numCorrect*100/numProblems);
           System.out.println(percent + " " + numCorrect + " " + numProblems);
           JOptionPane.showMessageDialog(null,"You got " + percent+ "%" + "\n" + "\n" +cnt.drawMap(PP) );// make netbeans showing stats and percent
			setVisible(false); //you can't see me!
			dispose(); //Destroy the JFrame object
			GradeChooser o = new GradeChooser();
   			o.setVisible(true);
   			o.isVisible();
       }
   }

   /**
    * @param args the command line arguments
    */
 //runs class and methods (runs screen typing area and button)
   public static void main(String args[]) {
       /* Set the Nimbus look and feel */
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
       /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
       try {
           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               if ("Nimbus".equals(info.getName())) {
                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   break;
               }
           }
       } catch (ClassNotFoundException ex) {
           java.util.logging.Logger.getLogger(questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (InstantiationException ex) {
           java.util.logging.Logger.getLogger(questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (IllegalAccessException ex) {
           java.util.logging.Logger.getLogger(questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (javax.swing.UnsupportedLookAndFeelException ex) {
           java.util.logging.Logger.getLogger(questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       }
       //</editor-fold>

       /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
               new questions(true, true, true, true, 6,7).setVisible(true);

           }
       });
   }

   // Variables declaration - do not modify
   private javax.swing.JButton jButton1;
   private javax.swing.JColorChooser jColorChooser1;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JProgressBar jProgressBar1;
   private javax.swing.JTextField jTextField1;
   // End of variables declaration
}
