package Mod;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
//Displays a users main menu and all the options available in the app once the user is signed in
public class MainMenu extends javax.swing.JFrame {

	private ArrayList <Integer> times = new ArrayList();
	private ArrayList <Integer> timesMin = new ArrayList();
	private int timesWokenUp = 0;
	
	//take and stores the hours in which noise was detected.
	public void setTimes(ArrayList<Integer> n) {
		times = n;
	}
	//take and stores the minute of an hour in which noise was detected.
	public void setTimesMin(ArrayList<Integer> n) {
		timesMin = n;
	}
	//take and stores the number of times noise was detected.
	public void setTimesWoke(int h) {
		timesWokenUp = h;
	}
	
	private User myUser;
	
	//allows user information to be passed from class to class (here allows for the setting of user information.
	public void setUser(User I) {
		myUser = I;
	}
    /**
     * Creates new form MainMenu
     */
	
	//Displays the main menu screen with all its components such as images and buttons
    public MainMenu() {
        initComponents();
        Dimension size = Toolkit. getDefaultToolkit(). getScreenSize();
        int scrnH = size.height;
        int scrnW = size.width;
        Dimension o =getSize();
        int Hdia = o.height/2;
        int Wdia = o.width/2;

        setLocation(scrnW/2-Wdia,scrnH/2-Hdia);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">       
    
  //Creates the main menu screen with all its components such as images and buttons
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlanetsArt3.png")));
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Tw Cen MT", 1, 11)); // NOI18N
        jButton1.setText("Personal Information");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tw Cen MT", 1, 11)); // NOI18N
        jButton2.setText("Analytics");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton3.setText("Begin Sleep");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton4.setText("Calendar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton5.setText("Improvement Plan");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton6.setText("Current Sleep");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 382, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(195, 195, 195))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1011, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(392, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    
    //if developed, would check if the calendar button was pressed and it would take the user to a screen with a calendar
    //and calendar functions.
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        
    
    //if developed it would check if the improvement plan button was clicked and it would take the user to the
    // improvement plan screen
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    //checks if the current sleep button is pressed, if so, information regarding times that sound was detected and the
    //number of times it was detected are passed into the next screen and the current sleep screen is displayed.
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	CurrentSleepSAcreen o = new CurrentSleepSAcreen();
    	String strForTimes = "These sounds took place at hours: ";
    	o.setUser(myUser);
    	 setVisible(false);
    	 o.setVisible(true);
    	 o.setTimesWoeknUp(timesWokenUp);
    	 for(int i =0; i<times.size(); i++) {
    		 if(i == times.size()-1) {
    			 strForTimes += times.get(i);
    			 strForTimes += ":";
    			 strForTimes += timesMin.get(i);
    		
    		 }
    		 else if(i == times.size()-2) {
    			 strForTimes += times.get(i);
    			 strForTimes += ":";
    			 strForTimes += timesMin.get(i);
    			 strForTimes += " and ";
    		 }
    		 else {
    			 strForTimes += times.get(i);
    			 strForTimes += ":";
    			 strForTimes += timesMin.get(i);
    			 strForTimes += ", ";
    		 }
    	 }
    	 o.jTextArea1.setText("You made Noise or woke up " + timesWokenUp + " times this night" + "\n" + "This is apporximately " + ((double)timesWokenUp)/6*100 + "% the ammount of times that the average American Wakes up at night" + "\n" + "\n" + strForTimes + " of the day");
    	 
 		o.isVisible();
    }                                        

    
    //Checks if the sleep button is pressed, if so, the user is taken to the begin sleep screen.
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	Sleep o = new Sleep();
    	o.setUser(myUser);
    	 setVisible(false);
    	 o.setVisible(true);
 		o.isVisible();
    }                                        

    //Checks if the analytics screen button is pressed, if so, information about pre-existing conditions is transfered and
    //and the user is taken to the analytics screen
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        analyticsScreen o = new analyticsScreen();
        int hours  = myUser.retConditionTimeAdd();
        o.setUser(myUser);
        setVisible(false);
        o.jTextArea1.setText("");
        if(hours > 5) {
        	hours = 5;
        }
        o.jTextArea1.setText("You stated to suffer from the following conditions: " + myUser.retConditionNames() + "The following tips may benefit you in your sleep: "+ "\n" + myUser.retConditionTips() + "\n" +"\n" + "Your conditions may affect the ammount of sleep you get, consider increasing your sleep by "+hours + " hours.");
        if(myUser.isObese()) {
        	o.jTextArea1.setText("You stated to suffer from the following conditions: " + myUser.retConditionNames() + "The following tips may benefit you in your sleep: "+ "\n" + myUser.retConditionTips() + "\n" + "You may also suffer from sleep disorders due to weight according to your calculated BMI. Ask your doctor for more treatments and information" +"\n"+"\n" + "Your conditions may affect the ammount of sleep you get, consider increasing your sleep by "+hours + " hours.");
        }
		o.setVisible(true);
		o.isVisible();
    }                                        

    //Checks if the personal information button is pressed, and if so, user is taken to personal information screen.
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         

        persoInfo o = new persoInfo();
        o.setUser(myUser);
        setVisible(false);
		o.setVisible(true);
		o.isVisible();
    }                                        

    /**
     * @param args the command line arguments
     */
    
  //Creates the main menu screen with all its components such as images and buttons
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration                   
}

